name: release

on:
  create:
    tags:
      - 'v*'
    branches:
      - master
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Metadata
        id: info
        run: |
          task info

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Promote Artifact
        run: |
          echo "Something happening"
