---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: build

on:
  push:
    branches:
      - master
      - main

permissions:
  id-token: write
  attestations: write
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version: '1.22'
          cache: false

      - name: Install dependencies
        working-directory: src
        run: go mod tidy

      - name: Run tests
        working-directory: src
        run: go test -v ./...

      - uses: anchore/sbom-action@e8d2a6937ecead383dfe75190d104edd1f9c5751 # v0
        with:
          path: ./src/
          format: 'spdx-json'
          output-file: 'source.sbom.spdx.json'
          artifact-name: 'source.sbom.spdx.json'

      - name: Display Source SBOM
        run: cat source.sbom.spdx.json

      - name: Build application
        working-directory: src
        run: go build -v -o example ./...

      - uses: actions/attest-sbom@3d6693daad97553949201f0913efcba833e58d67 # v1
        with:
          subject-path: './src/example'
          sbom-path: 'source.sbom.spdx.json'

      - uses: anchore/sbom-action@e8d2a6937ecead383dfe75190d104edd1f9c5751 # v0
        with:
          file: ./src/example
          format: 'spdx-json'
          output-file: 'package.sbom.spdx.json'
          artifact-name: 'package.sbom.spdx.json'

      - uses: actions/attest-sbom@3d6693daad97553949201f0913efcba833e58d67 # v1
        with:
          subject-path: './src/example'
          sbom-path: 'package.sbom.spdx.json'

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@bdd51370e0416ac948727f861e03c2f05d32d78e # v1
        with:
          subject-path: './src/example'

      - name: Upload build artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: example
          path: ./src

  package:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install Task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Collect Metadata
        id: info
        run: task info

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # v2
        id: build-image
        with:
          build-args: |
            VERSION=${{ steps.info.outputs.version }}
            SHA=${{ github.sha }}
          context: ./src
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/example:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository }}/example:latest

      - uses: anchore/sbom-action@e8d2a6937ecead383dfe75190d104edd1f9c5751 # v0
        with:
          image: ${{ env.REGISTRY }}/${{ github.repository }}/example:${{ github.sha }}
          format: 'spdx-json'
          output-file: 'image.sbom.spdx.json'
          artifact-name: 'image.sbom.spdx.json'

      - name: Display Image SBOM
        run: cat image.sbom.spdx.json

      - uses: actions/attest-sbom@3d6693daad97553949201f0913efcba833e58d67 # v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository }}/example
          subject-digest: ${{ steps.build-image.outputs.digest }}
          sbom-path: 'image.sbom.spdx.json'
          push-to-registry: true

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@bdd51370e0416ac948727f861e03c2f05d32d78e # v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository }}/example
          subject-digest:  ${{ steps.build-image.outputs.digest }}
          push-to-registry: true
