name: build

on:
  push:
    branches:
      - main

env:
    GHCR_REPO: "ghcr.io/xunholy/${{ github.event.repository.name }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install Crane
      - uses: imjasonh/setup-crane@v0.3

      # Install Cosign
      - uses: sigstore/cosign-installer@main

      - name: Install Task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Get Metadata
        id: info
        run: |
          task info

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        if: github.ref != 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VERSION=${{ steps.info.outputs.version }}
            SHA=${{ github.sha }}
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/xunholy/${{ github.event.repository.name }}/example:${{ github.sha }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29

      # Cosign the OCI artifact
      - name: Sign the OCI artifact
        run: cosign attest --predicate predecates/lint.json $GHCR_REPO@${{ steps.crane.outputs.DIGEST }} -y

      # Cosign the OCI artifact
      - name: Sign the OCI artifact
        run: cosign sign $GHCR_REPO@${{ steps.crane.outputs.DIGEST }} -y
