---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: build

on:
  push:
    branches:
      - master
      - main

permissions:
  id-token: write
  attestations: write
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      COSIGN_EXPERIMENTAL: "true"
      COSIGN_YES: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: Install dependencies
        working-directory: src
        run: go mod tidy

      - name: Run tests
        working-directory: src
        run: go test -v ./...

      - uses: anchore/sbom-action@v0
        with:
          path: ./src/
          format: 'spdx-json'
          output-file: 'source.sbom.spdx.json'

      - name: Display Source SBOM
        run: cat source.sbom.spdx.json

      - name: Build application
        working-directory: src
        run: go build -v -o example ./...

      - uses: actions/attest-sbom@v1
        with:
          subject-path: './src/example'
          sbom-path: 'source.sbom.spdx.json'

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: './src/example'

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ./src/example
          path: ./src/example
