---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: build

on:
  push:
    branches:
      - master
      - main

permissions:
  id-token: write
  attestations: write
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      COSIGN_EXPERIMENTAL: "true"
      COSIGN_YES: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - uses: anchore/sbom-action@v0
        with:
          path: ./src/
          format: 'spdx-json'
          output-file: 'source.sbom.spdx.json'

      # - uses: actions/attest-sbom@v1
      #   with:
      #     subject-path: 'bin/my-artifact.tar.gz'
      #     sbom-path: 'sbom.spdx.json'

      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-path: 'PATH/TO/ARTIFACT'

      - name: Display Source SBOM
        run: cat source.sbom.spdx.json

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Collect Metadata
        id: info
        run: task info

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v2
        id: build-image
        with:
          build-args: |
            VERSION=${{ steps.info.outputs.version }}
            SHA=${{ github.sha }}
          context: ./src
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/example:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository }}/example:latest

      - uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY }}/${{ github.repository }}/example:${{ github.sha }}
          format: 'spdx-json'
          output-file: 'image.sbom.spdx.json'

      - uses: actions/attest-sbom@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository }}/example:${{ github.sha }}
          subject-digest: ${{ steps.build-image.outputs.digest }}
          sbom-path: 'image.sbom.spdx.json'
          push-to-registry: true

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository }}/example:${{ github.sha }}
          subject-digest:  ${{ steps.build-image.outputs.digest }}
          push-to-registry: true
