---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Schedule: Renovate"

on:
  workflow_dispatch:
    inputs:
      # https://docs.renovatebot.com/self-hosted-configuration/#dryrun
      dryRun:
        description: "Dry Run"
        default: "false"
        required: false
      # https://docs.renovatebot.com/examples/self-hosting/#about-the-log-level-numbers
      logLevel:
        description: "Log Level"
        default: "debug"
        required: false
      version:
        description: Renovate version
        default: latest
        required: false
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - master
      - main
    paths:
      - .github/workflows/renovate.yml
      - .github/renovate.json5

env:
  LOG_LEVEL: "${{ inputs.logLevel || 'debug' }}"
  RENOVATE_DRY_RUN: "${{ inputs.dryRun == true }}"
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
  WORKFLOW_RENOVATE_VERSION: "${{ inputs.version || 'latest' }}"
  RENOVATE_USERNAME: "${{ secrets.BOT_USERNAME }}[bot]"
  RENOVATE_GIT_AUTHOR: "${{ secrets.BOT_USERNAME }} <${{ secrets.BOT_USER_ID }}+${{ secrets.BOT_USERNAME }}[bot]@users.noreply.github.com>"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Validate Renovate Configuration
        uses: suzuki-shunsuke/github-action-renovate-config-validator@b54483862375f51910a60c4f498e927d4f3df466 # v1.0.1

      - name: Generate Token
        uses: actions/create-github-app-token@ad38cffc07bac6e3857755914c4c88bfd2db4da4 # v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_ID }}"

      - run: echo ${{ steps.app-auth.outputs.app-slug }}

      - name: Renovate
        uses: renovatebot/github-action@21d88b0bf0183abcee15f990011cca090dfc47dd # v40.1.12
        with:
          configurationFile: .github/renovate.json5
          token: "x-access-token:${{ steps.app-token.outputs.token }}"
          renovate-version: "${{ env.WORKFLOW_RENOVATE_VERSION }}"
